name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }} 

      # ★★★ 新しい詳細デバッグ用のステップ（修正済み） ★★★
      - name: Debug: List files in root directory
        run: ls -la

      - name: Debug: List files in BingoApp_typescript directory
        run: ls -la BingoApp_typescript/

      - name: Debug: Find package.json within BingoApp_typescript recursively
        run: find BingoApp_typescript -name "package.json" # この行のインデントを修正
        
      - name: Debug: Check for package.json in BingoApp_typescript direct path
        run: test -f BingoApp_typescript/package.json && echo "package.json found at direct path!" || echo "package.json NOT found at direct path!"
      # ★★★ ここまでデバッグ用のステップ ★★★

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install dependencies for BingoApp_typescript
        run: npm install
        working-directory: BingoApp_typescript

      - name: Build project
        run: npm run build
        working-directory: BingoApp_typescript

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./ 
