name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}
          token: ${{ secrets.GITHUB_TOKEN }} 

      # ★★★ 簡略化されたデバッグ用のステップ ★★★
      - name: Debug: List files and check package.json
        run: |
          echo "Listing files in root directory:"
          ls -la
          echo "Listing files in BingoApp_typescript directory:"
          ls -la BingoApp_typescript/
          echo "Checking for package.json in BingoApp_typescript:"
          find BingoApp_typescript -name "package.json"
          test -f BingoApp_typescript/package.json && echo "package.json found at direct path!" || echo "package.json NOT found at direct path!"
      # ★★★ ここまでデバッグ用のステップ ★★★

      - name: Set up Node.js 
        uses: actions/setup-node@v4
        with:
          node-version: '22.17.0'

      - name: Install dependencies for BingoApp_typescript
        run: npm install
        working-directory: BingoApp_typescript

      - name: Build project
        run: npm run build
        working-directory: BingoApp_typescript

      - name: Deploy to GitHub Pages 
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          #publish_dir: ./ 
